### ISSUE TITLE
features missing

### ISSUE THREAD

**Issue by CBgaming07** [TheCuteOwl/Trap-Stealer#59]
I seem to be missing some of the feature such as the whatsapp stealer

**Comment by 9borz** [comment]
> No more support provided

why do you deobfuscate my grabber to send me message ?

**Comment by TheCuteOwl** [comment]
Why do you dualhook some repository?

**Comment by 9borz** [comment]
> Why do you dualhook some repository?

So does what I do bother you? and "Epsilon-Stealer" don't ?

**Comment by 9borz** [comment]
> It is too, even worse than you, because they update it frequently, and yes, github is not a place to put malware everywhere, your suppose to show the src

yeah you right i'm gonna delete my github but can you add me in discord juste for ask some question in python ?

**Comment by TheCuteOwl** [comment]
Thanks for deleting your repo, and sadly i got banned out of discord and dont really use it anymore, maybe just talk here for any help

**Comment by 9borz** [comment]
> Thanks for deleting your repo, and sadly i got banned out of discord and dont really use it anymore, maybe just talk here for any help

you don't gave another social media ? it want ask many question

**Comment by TheCuteOwl** [comment]
sadly no

**Comment by 9borz** [comment]
ok I will ask the question here
1. how did you learn ptyhon and when
how you learned (video, website, training, course or study?)
and what was your discipline in learning I mean, if you learned more the theory of practice or the opposite and if you learned with practice how you use practice, code war or something like that
2.how did you manage to move forward I mean, for example I always have the impression of stagnating and staying on the same theme and I never have the impression that I am improving or that I am learning from The advantage is that I'm afraid of going too far and forgetting the basics, you know what I mean?
3. I know it's a lot of questions and you're probably not going to answer me or you're going to write 2 or 3 words but I'll continue because you seem to have worked a lot in python, so the third question is how do you manage to projects, how do you approach them, and how to learn and improve with small projects?
I know I did something bad and fortunately I didn't do much with the information, thank you anyway and thank you for echoing me

**Comment by TheCuteOwl** [comment]
Well, i've learned python pretty easily, self learning, just give yourself objective and do it, like for Trap I just wanted to make a stealer, I didnt feel like i've move forward, i still do the same thing and finally, i dont really improve stuff, just make them less shitty

**Comment by 9borz** [comment]
> Well, i've learned python pretty easily, self learning, just give yourself objective and do it, like for Trap I just wanted to make a stealer, I didnt feel like i've move forward, i still do the same thing and finally, i dont really improve stuff, just make them less shitty

thank you for your answer it will really help me

**Comment by TheCuteOwl** [comment]
Not sure aboyut this but np

**Comment by 9borz** [comment]
> Not sure aboyut this but np

I needed someone to tell me how they learn because I felt like I was learning poorly
