### ISSUE TITLE
No proof

### ISSUE THREAD

**Issue by EmpirePlugins** [TheCuteOwl/Trap-Stealer#6]
Virus I cried after

**Comment by TheCuteOwl** [comment]
Before saying this give proof please

**Comment by EmpirePlugins** [comment]
1 your profile picture 2 your an unloved faggot, your built like a mini van you fat cunt

**Comment by TheCuteOwl** [comment]
This is not a malware proof haha

**Comment by EmpirePlugins** [comment]
Amazin

**Comment by TheCuteOwl** [comment]
So no proof?

**Comment by Azuuu1** [comment]
bro what u talking about u have no proof look at ur shit bro hes profile iis u on the streets tryna sell ur self for 9,99 what u talking about when u step on a scale it doesnt show anything because it got broken cus of ur fat ass ur a 10 yr old tryna get "logs "
u have a litteraly a rat a public one in ur repository bro u really want that roblox logs XDDDD
